;;;; termite-match.import.scm - GENERATED BY CHICKEN 4.8.0.5 -*- Scheme -*-

(eval '(import
         chicken
         scheme
         srfi-1
         srfi-4
         srfi-18
         mailbox
         mailbox-threads
         tcp
         extras
         posix
         ports
         defstruct
         (prefix lookup-table chicken:)
         (prefix s11n s11n:)))
(##sys#register-compiled-module
  'termite-match
  (list)
  '()
  (list (cons 'match
              (##sys#er-transformer
                (##core#lambda
                  (x r c)
                  (let ((datum (cadr x))
                        (clauses (cddr x))
                        (tmp (r 'tmp))
                        (fail (r 'fail))
                        (%lambda (r 'lambda))
                        (%let* (r 'let*))
                        (%raise (r 'raise))
                        (%list (r 'list)))
                    `(,%let*
                      ((,tmp ,datum)
                       (,fail
                        (,%lambda () (,%raise (,%list bad-match: ,tmp)))))
                      ,(compile-pattern-match #f `(,fail) clauses tmp))))))
        (cons 'match/action
              (##sys#er-transformer
                (##core#lambda
                  (x r c)
                  (let ((on-success (cadr x))
                        (on-fail (caddr x))
                        (datum (cadddr x))
                        (clauses (cddddr x))
                        (%let (r 'let))
                        (%tmp (r 'tmp))
                        (%succ (r 'succ))
                        (%fail (r 'fail))
                        (%lambda (r 'lambda)))
                    `(,%let
                      ((,%tmp ,datum)
                       (,%succ (,%lambda () ,on-success))
                       (,%fail (,%lambda () ,on-fail)))
                      ,(compile-pattern-match
                         `(,%succ)
                         `(,%fail)
                         clauses
                         %tmp)))))))
  (list))

;; END OF FILE
